name: sfds
description: "Steve's Flutter Design System"
version: 0.1.0
homepage: https://github.com/SDC-Consulting-BE/sfds

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  firebase_core: ^4.2.1
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.0
  package_info_plus: ^9.0.0
  riverpod_annotation: ^3.0.3
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
